import { Top50Songs } from "../models/interfaces/music/types";

export const top50SongsData: Top50Songs[] = [
  {
    title: "Echoes of Time",
    artist: "Aurora Sky",
    artistId: 1,
    album: "Timeless Journey",
    albumId: 101,
    genre: "Ambient",
    release_year: 2021,
    duration: "4:32",
    image: "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    audioUrl: './store/songs/Audio Examples_2.mp3',
    ratings: 4.5,
  },
  {
    title: "Midnight Drive",
    artist: "Neon Waves",
    artistId: 2,
    album: "City Lights",
    albumId: 102,
    genre: "Synthwave",
    release_year: 2020,
    duration: "3:45",
    audioUrl: './store/songs/Audio Examples_1.mp3',
    image: "https://plus.unsplash.com/premium_photo-1682294457124-ca66684678dc?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ratings: 4.0,
  },
  {
    title: "Desert Mirage",
    artist: "Sandstorm",
    artistId: 3,
    album: "Oasis Dreams",
    albumId: 103,
    genre: "Electronic",
    release_year: 2019,
    duration: "5:01",
    image: "https://images.unsplash.com/photo-1508186736123-44a5fcb36f9f?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    audioUrl: './store/songs/Audio Examples_3.mp3',
    ratings: 4.7,
  },
  {
    title: "Mountain Whisper",
    artist: "Echoing Pines",
    artistId: 4,
    album: "Nature's Call",
    albumId: 104,
    genre: "Folk",
    release_year: 2022,
    duration: "4:18",
    image: "",
    audioUrl: './store/songs/Audio Examples_4.mp3',
    ratings: 4.3,
  },
  {
    title: "Golden Sunrise",
    artist: "Sunset Groove",
    artistId: 5,
    album: "Morning Bliss",
    albumId: 105,
    genre: "Pop",
    release_year: 2021,
    duration: "3:52",
    image: "",
    ratings: 4.6,
    audioUrl: "./store/songs/Audio Examples_5.mp3"
  },
  {
    title: "Ocean's Roar",
    artist: "Tidal Waves",
    artistId: 6,
    album: "Deep Blue",
    albumId: 106,
    genre: "Rock",
    release_year: 2018,
    duration: "5:27",
    image: "",
    ratings: 4.8,
    audioUrl: "./store/songs/Audio Examples_6.mp3"
  },
  {
    title: "Starlit Night",
    artist: "Celestial Harmony",
    artistId: 7,
    album: "Galactic Dreams",
    albumId: 107,
    genre: "Ambient",
    release_year: 2020,
    duration: "4:45",
    image: "",
    ratings: 4.9,
    audioUrl: "./store/songs/Audio Examples_7.mp3"
  },
  {
    title: "Electric Pulse",
    artist: "Voltage Surge",
    artistId: 8,
    album: "Power Grid",
    albumId: 108,
    genre: "Electronic",
    release_year: 2019,
    duration: "3:58",
    image: "",
    ratings: 4.4,
    audioUrl: "./store/songs/Audio Examples_8.mp3"
  },
  {
    title: "Rainy Day Blues",
    artist: "Thunderstorm",
    artistId: 9,
    album: "Stormy Weather",
    albumId: 109,
    genre: "Blues",
    release_year: 2022,
    duration: "4:10",
    image: "",
    ratings: 4.2,
    audioUrl: "./store/songs/Audio Examples_9.mp3"
  },
  {
    title: "City Lights",
    artist: "Urban Beats",
    artistId: 10,
    album: "Concrete Jungle",
    albumId: 110,
    genre: "Hip-Hop",
    release_year: 2021,
    duration: "3:29",
    image: "",
    ratings: 4.0,
    audioUrl: "./store/songs/Audio Examples_10.mp3"
  },
  {
    title: "Forest Serenade",
    artist: "Wildlife",
    artistId: 11,
    album: "Wilderness",
    albumId: 111,
    genre: "Folk",
    release_year: 2018,
    duration: "4:36",
    image: "",
    ratings: 4.3,
    audioUrl: "./store/songs/Audio Examples_11.mp3"
  },
  {
    title: "Solar Flare",
    artist: "Astroglide",
    artistId: 12,
    album: "Cosmic Rays",
    albumId: 112,
    genre: "Synthwave",
    release_year: 2020,
    duration: "3:40",
    image: "",
    ratings: 4.5,
    audioUrl: "./store/songs/Audio Examples1.mp3"
  },
  {
    title: "Heartbeat",
    artist: "Pulse Rhythm",
    artistId: 13,
    album: "Vital Signs",
    albumId: 113,
    genre: "Pop",
    release_year: 2021,
    duration: "3:22",
    image: "",
    ratings: 4.6,
    audioUrl: "./store/songs/SoundHelix-Song-3.mp3"
  },
  {
    title: "Misty Mountains",
    artist: "Echo Canyon",
    artistId: 14,
    album: "Rocky Trails",
    albumId: 114,
    genre: "Rock",
    release_year: 2019,
    duration: "4:50",
    image: "",
    ratings: 4.7,
    audioUrl: "./store/songs/Audio Examples.mp3"
  },
  {
    title: "Things-Fall-Apart",
    artist: "Kofi-Kinaata",
    artistId: 15,
    album: "Northern Lights",
    albumId: 115,
    genre: "Ambient",
    release_year: 2021,
    duration: "5:05",
    image: "",
    ratings: 4.8,
    audioUrl: "./store/songs/Kofi-Kinaata-Things-Fall-Apart.mp3"
  },
  // {
  //   title: "Neon Dreams",
  //   artist: "RetroWave",
  //   artistId: 16,
  //   album: "Flashback",
  //   albumId: 116,
  //   genre: "Synthwave",
  //   release_year: 2020,
  //   duration: "4:02",
  //   image: "",
  //   ratings: 4.4,
  //   audioUrl: ""
  // },
  // {
  //   title: "Waves of Time",
  //   artist: "Oceanic",
  //   artistId: 17,
  //   album: "Eternal Sea",
  //   albumId: 117,
  //   genre: "Ambient",
  //   release_year: 2021,
  //   duration: "4:44",
  //   image: "",
  //   ratings: 4.9,
  //   audioUrl: ""
  // },
  // {
  //   title: "Crimson Sunset",
  //   artist: "Red Horizon",
  //   artistId: 18,
  //   album: "Dusk",
  //   albumId: 118,
  //   genre: "Rock",
  //   release_year: 2019,
  //   duration: "5:18",
  //   image: "",
  //   ratings: 4.7,
  //   audioUrl: ""
  // },
  // {
  //   title: "Desert Winds",
  //   artist: "Sand Dunes",
  //   artistId: 19,
  //   album: "Sahara Nights",
  //   albumId: 119,
  //   genre: "Electronic",
  //   release_year: 2018,
  //   duration: "4:15",
  //   image: "",
  //   ratings: 4.2,
  //   audioUrl: ""
  // },
  // {
  //   title: "Mystic River",
  //   artist: "Deep Waters",
  //   artistId: 20,
  //   album: "Flow",
  //   albumId: 120,
  //   genre: "Ambient",
  //   release_year: 2020,
  //   duration: "4:27",
  //   image: "",
  //   ratings: 4.5,
  //   audioUrl: ""
  // },
  // {
  //   title: "Urban Jungle",
  //   artist: "Concrete Rhythm",
  //   artistId: 21,
  //   album: "City Vibes",
  //   albumId: 121,
  //   genre: "Hip-Hop",
  //   release_year: 2021,
  //   duration: "3:34",
  //   image: "",
  //   ratings: 4.3,
  //   audioUrl: ""
  // },
  // {
  //   title: "Solar Winds",
  //   artist: "Galactic Voyage",
  //   artistId: 22,
  //   album: "Stellar Journey",
  //   albumId: 122,
  //   genre: "Synthwave",
  //   release_year: 2019,
  //   duration: "4:06",
  //   image: "",
  //   ratings: 4.6,
  //   audioUrl: ""
  // },
  // {
  //   title: "Silver Moon",
  //   artist: "Lunar Echoes",
  //   artistId: 23,
  //   album: "Nightfall",
  //   albumId: 123,
  //   genre: "Ambient",
  //   release_year: 2022,
  //   duration: "4:53",
  //   image: "",
  //   ratings: 4.8,
  //   audioUrl: ""
  // },
  // {
  //   title: "Golden Hour",
  //   artist: "Sunset Vibes",
  //   artistId: 24,
  //   album: "Evening Glow",
  //   albumId: 124,
  //   genre: "Pop",
  //   release_year: 2020,
  //   duration: "3:43",
  //   image: "",
  //   ratings: 4.4,
  //   audioUrl: ""
  // },
  // {
  //   title: "Mountain Echo",
  //   artist: "High Peaks",
  //   artistId: 25,
  //   album: "Summit",
  //   albumId: 125,
  //   genre: "Rock",
  //   release_year: 2019,
  //   duration: "4:48",
  //   image: "",
  //   ratings: 4.5,
  //   audioUrl: ""
  // },
  // {
  //   title: "River of Dreams",
  //   artist: "Sleepwalker",
  //   artistId: 26,
  //   album: "Night Visions",
  //   albumId: 126,
  //   genre: "Ambient",
  //   release_year: 2021,
  //   duration: "5:12",
  //   image: "",
  //   ratings: 4.9,
  //   audioUrl: ""
  // },
  // {
  //   title: "Night Drive",
  //   artist: "Midnight Ride",
  //   artistId: 27,
  //   album: "Road Trip",
  //   albumId: 127,
  //   genre: "Synthwave",
  //   release_year: 2020,
  //   duration: "4:00",
  //   image: "",
  //   ratings: 4.3,
  //   audioUrl: ""
  // },
  // {
  //   title: "Desert Rose",
  //   artist: "Cactus Bloom",
  //   artistId: 28,
  //   album: "Oasis",
  //   albumId: 128,
  //   genre: "Folk",
  //   release_year: 2018,
  //   duration: "4:25",
  //   image: "",
  //   ratings: 4.7,
  //   audioUrl: ""
  // },
  // {
  //   title: "Skyline",
  //   artist: "Urban Pulse",
  //   artistId: 29,
  //   album: "City Nights",
  //   albumId: 129,
  //   genre: "Hip-Hop",
  //   release_year: 2021,
  //   duration: "3:30",
  //   image: "",
  //   ratings: 4.2,
  //   audioUrl: ""
  // },
  // {
  //   title: "Cosmic Journey",
  //   artist: "Stellar Drift",
  //   artistId: 30,
  //   album: "Nebula",
  //   albumId: 130,
  //   genre: "Synthwave",
  //   release_year: 2019,
  //   duration: "4:12",
  //   image: "",
  //   ratings: 4.5,
  //   audioUrl: ""
  // },
  // {
  //   title: "Golden Leaves",
  //   artist: "Autumn Whisper",
  //   artistId: 31,
  //   album: "Fall Breeze",
  //   albumId: 131,
  //   genre: "Folk",
  //   release_year: 2022,
  //   duration: "4:30",
  //   image: "",
  //   ratings: 4.6,
  //   audioUrl: ""
  // },
  // {
  //   title: "Sunset Boulevard",
  //   artist: "Neon Lights",
  //   artistId: 32,
  //   album: "City Dreams",
  //   albumId: 132,
  //   genre: "Pop",
  //   release_year: 2021,
  //   duration: "3:47",
  //   image: "",
  //   ratings: 4.4,
  //   audioUrl: ""
  // },
  // {
  //   title: "Ocean Breeze",
  //   artist: "Coastal Waves",
  //   artistId: 33,
  //   album: "Shoreline",
  //   albumId: 133,
  //   genre: "Ambient",
  //   release_year: 2020,
  //   duration: "4:41",
  //   image: "",
  //   ratings: 4.8,
  //   audioUrl: ""
  // },
  // {
  //   title: "Moonlit Dance",
  //   artist: "Lunar Beats",
  //   artistId: 34,
  //   album: "Starlight",
  //   albumId: 134,
  //   genre: "Electronic",
  //   release_year: 2019,
  //   duration: "3:55",
  //   image: "",
  //   ratings: 4.3,
  //   audioUrl: ""
  // },
  // {
  //   title: "Forest Echoes",
  //   artist: "Whispering Pines",
  //   artistId: 35,
  //   album: "Woodland",
  //   albumId: 135,
  //   genre: "Folk",
  //   release_year: 2018,
  //   duration: "4:19",
  //   image: "",
  //   ratings: 4.5,
  //   audioUrl: ""
  // },
  // {
  //   title: "City Pulse",
  //   artist: "Urban Flow",
  //   artistId: 36,
  //   album: "Concrete Jungle",
  //   albumId: 136,
  //   genre: "Hip-Hop",
  //   release_year: 2021,
  //   duration: "3:28",
  //   image: "",
  //   ratings: 4.1,
  //   audioUrl: ""
  // },
  // {
  //   title: "Desert Sky",
  //   artist: "Mirage",
  //   artistId: 37,
  //   album: "Sahara",
  //   albumId: 137,
  //   genre: "Electronic",
  //   release_year: 2019,
  //   duration: "4:05",
  //   image: "",
  //   ratings: 4.6,
  //   audioUrl: ""
  // },
  // {
  //   title: "Mountain Air",
  //   artist: "Summit Winds",
  //   artistId: 38,
  //   album: "Peaks",
  //   albumId: 138,
  //   genre: "Rock",
  //   release_year: 2022,
  //   duration: "5:20",
  //   image: "",
  //   ratings: 4.7,
  //   audioUrl: ""
  // },
  // {
  //   title: "Neon City",
  //   artist: "Urban Lights",
  //   artistId: 39,
  //   album: "Metropolis",
  //   albumId: 139,
  //   genre: "Synthwave",
  //   release_year: 2020,
  //   duration: "3:48",
  //   image: "",
  //   ratings: 4.4,
  //   audioUrl: ""
  // },
  // {
  //   title: "Golden Horizon",
  //   artist: "Sunset Glow",
  //   artistId: 40,
  //   album: "Evening Sky",
  //   albumId: 140,
  //   genre: "Pop",
  //   release_year: 2021,
  //   duration: "3:51",
  //   image: "",
  //   ratings: 4.5,
  //   audioUrl: ""
  // },
  // {
  //   title: "Silent Waters",
  //   artist: "Calm Tide",
  //   artistId: 41,
  //   album: "Serenity",
  //   albumId: 141,
  //   genre: "Ambient",
  //   release_year: 2019,
  //   duration: "5:09",
  //   image: "",
  //   ratings: 4.8,
  //   audioUrl: ""
  // },
  // {
  //   title: "Crimson Sky",
  //   artist: "Red Dawn",
  //   artistId: 42,
  //   album: "Twilight",
  //   albumId: 142,
  //   genre: "Rock",
  //   release_year: 2020,
  //   duration: "4:51",
  //   image: "",
  //   ratings: 4.6,
  //   audioUrl: ""
  // },
  // {
  //   title: "Mystic Valley",
  //   artist: "Enchanted Hills",
  //   artistId: 43,
  //   album: "Secret Paths",
  //   albumId: 143,
  //   genre: "Folk",
  //   release_year: 2018,
  //   duration: "4:17",
  //   image: "",
  //   ratings: 4.7,
  //   audioUrl: ""
  // },
  // {
  //   title: "Urban Rhythm",
  //   artist: "City Beats",
  //   artistId: 44,
  //   album: "Street Vibes",
  //   albumId: 144,
  //   genre: "Hip-Hop",
  //   release_year: 2021,
  //   duration: "3:33",
  //   image: "",
  //   ratings: 4.3,
  //   audioUrl: ""
  // },
];
